#lang racket

(define a 1103515245)
(define b 12345)
(define m (expt 2 31))
(define (rand-update x)
	(remainder (+ (* a x) b) m))

(define rand
	(let ((seed (random 0 10000)))
		(lambda (m)	
			(cond
				((eq? m 'generate)
					(let ((new (rand-update seed)))
						(begin (set! seed new)
								new)))
				((eq? m 'reset)
					(lambda (new)
						(set! seed new)))
				(else (error "Unknown instruction: " m))))))
((rand 'reset) 1)
(rand 'generate)
(rand 'generate)
(rand 'generate)
(newline)
((rand 'reset) 10)
(rand 'generate)
(rand 'generate)
(rand 'generate)
(newline)
((rand 'reset) 10)
(rand 'generate)
(rand 'generate)
(rand 'generate)